lumirlumir/lumirlumir-configs:
  - source: ./.github/sync-client.yml
    dest: ./clients/web-moing.lumir.page.yml
  # ./.github/workflows
  - source: ./.github/workflows/sync-client.yml
    dest: ./configs/.github/workflows/sync-client.yml
  # ./.github
  - source: ./.github/CODEOWNERS
    dest: ./configs/.github/CODEOWNERS
  # ./
  - source: ./.editorconfig
    dest: ./configs/.editorconfig
  - source: ./.nvmrc
    dest: ./configs/.nvmrc
  - source: ./.prettierignore
    dest: ./configs/.prettierignore
  - source: ./CODE_OF_CONDUCT.md
    dest: ./configs/CODE_OF_CONDUCT.md
  - source: ./jsconfig.json
    dest: ./configs/jsconfig.json
  - source: ./VScode.code-workspace
    dest: ./configs/VScode.code-workspace
